### ISSUE TITLE
is there any way to export the results?

### ISSUE THREAD

**Issue by hackerhero0x01** [CYS4srl/SensitiveDiscoverer#23]
I don't see any option to export/save result,is there any way?

**Comment by beryxz** [comment]
At the moment, the scan results cannot be exported. But, considering this feature might be helpful, it could be implemented in a future release.

I suggest exporting directly to CSV as is done with the regexes lists.

**Comment by beryxz** [comment]
Added the option to export the results as either CSV or JSON.

**Comment by hackerhero0x01** [comment]
Awesome! Thanks a lot :)
