### ISSUE TITLE
Improve context menu

### ISSUE THREAD

**Issue by jaikishantulswani** [CYS4srl/SensitiveDiscoverer#38]
@beryxz Need some context menu feature to send `from proxy to sensitivediscovere`  or having type of `radiobox` or `checkbox` to use `passive` scanning feature too

**Comment by beryxz** [comment]
Refer to #41

**Comment by jaikishantulswani** [comment]
@beryxz Thank you for the improvement but I am facing an issue while loading custom regex list in csv format which is not getting loaded.

**Comment by beryxz** [comment]
@jaikishantulswani Please, open another issue and provide the following:
- The extension version
- An example of a CSV file that is not loaded correctly
