### ISSUE TITLE
unable to scan 

### ISSUE THREAD

**Issue by Abhinav217-seed** [CYS4srl/SensitiveDiscoverer#64]
what version burpsuite is required to run this extension i was unable to use this extension in my burp

**Comment by beryxz** [comment]
It surely runs on the latest stable version. But it should also work just
fine on some previous ones.

Please include some more detailed information on your system, the burp
version, and the extension version you are using

**Comment by beryxz** [comment]
I'd suggest switching to a newer Burp version. Versions >= 2023.12.1 work correctly.
If the problem persists, please provide more detailed information from the burp and extension logs.
