### ISSUE TITLE
Feature request: automatically remove exact duplicates from logger

### ISSUE THREAD

**Issue by L1-0** [CYS4srl/SensitiveDiscoverer#65]
Hi, right now i'm getting a lot of hits where all four fields have multiples of exact the same content, i would appreciate if there was some form of duplicate detection, where i wouldn't have to work through tons of the exact same entries. Screenshot appended.

Maybe you can check if all four fields with the same value are already contained in the logger window.

![grafik](https://github.com/user-attachments/assets/8f20f6f6-7613-4784-a608-1b8fea303b18)

**Comment by beryxz** [comment]
Hi, thanks for your input.

 I've added a new "Unique results" checkbox in the Logger tab to filter the results so they do not show duplicates. This feature is in the latest release ([v4.2.0](https://github.com/CYS4srl/SensitiveDiscoverer/releases/tag/v4.2.0))
